name: bond
description: Bond project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter


  # Bond packages
  bond_core: ^0.0.2
  bond_network: ^0.0.3
  bond_cache: ^0.0.2
  bond_form: ^0.0.1+30
  bond_form_riverpod: ^0.0.1+3
  bond_app_analytics: ^0.0.1+3
  bond_notifications: ^0.0.1


  get_it: ^7.2.0
  open_store: ^0.5.0


  # network
  dio: ^5.2.1+1
  pretty_dio_logger: ^1.1.1

  # serialization
  json_serializable: ^6.5.4
  json_annotation: ^4.7.0

  #ui
  flutter_svg: ^1.0.3
  google_fonts: ^5.0.0

  # state management
  flutter_riverpod: ^2.5.1
  equatable: ^2.0.5

  # navigation
  go_router: ^10.1.1

  # utils
  flutter_native_splash: ^2.2.8
  device_info_plus: ^10.0.1
  faker: ^2.1.0

  # platforms packages
  universal_platform: ^1.0.0+1
  shared_preferences: ^2.0.15
  flutter_secure_storage: ^8.0.0
  package_info_plus: ^4.0.2
  flutter_local_notifications: ^9.3.3
  in_app_review: ^2.0.6
  share_plus: ^7.0.2

  # Firebase
  firebase_analytics: ^11.2.0
  firebase_core: ^3.2.0
  firebase_messaging: ^15.0.3
  firebase_crashlytics: ^4.0.3
  firebase_remote_config: ^5.0.3

  # localization
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  build_runner: ^2.3.2
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/icons/
    - assets/images/